#!/bin/bash

_rdc_completions() {
	# If there's already an argument after the command, do nothing
	if [ "${#COMP_WORDS[@]}" != "2" ]; then
		return
	fi
	filenames=""
	is_first=1
	for fileroute in ~/Remotes/*; do
		filename=$(echo $fileroute | awk -F / '{ print $NF }')
		if [ $is_first != 1 ]; then
			filenames+=' '
		fi
		filenames+=$filename
		is_first=0
	done
	COMPREPLY=($(compgen -W "$filenames" "${COMP_WORDS[1]}"))
}
complete -F _rdc_completions rdc
